### ISSUE TITLE
upgrade建议增加一个下载路径选择参数

### ISSUE THREAD

**Issue by toddlerya** [chenjiandongx/pls#1]
当前默认下载到用户目录的`.command`文件夹内，可以考虑增加一个参数让用户自己选择在哪里创建`.command`来存放下载好的markdown文件（比如下载到和`pls_windows_amd64.exe`同级目录）。  
之所以提出这个需求，是因为考虑到有用户的使用环境为企业内网，与互联网隔绝，通常这些用户都是在外网更新后，打包将程序和数据文件传入内网使用~我就是这种用户 :）

**Comment by chenjiandongx** [comment]
@toddlerya 

也不是说不行，那样就得每次使用 `pls` 命令的时候另外加上一个类似 `-d(--directory)` 的参数来指定路径了。今天会发一个新版本提供该功能。

**Comment by chenjiandongx** [comment]
v0.1.3 版本已发布，新增 -d 参数用于指定命令文件夹位置
